name: DevOps Assessment

on:
  push:
    branches:
      - main

jobs:
  devops-assessment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build -t first-devops-docker/first-devops-assessment .
          docker push first-devops-docker/first-devops-assessment/hafizshaikh


          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"

          git add .
          git commit -m "updating newer image"
          git push --set-upstream origin main
