on:
  push:
    branches:
      - main

jobs:
  devops-assessment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub and push Docker image
        run: |
          docker login --username hafizshaikh --password Wohlig@123 && \
          docker build -t hafizshaikh/newimage2:first-devops-assessment-latest . && \
          docker push hafizshaikh/newimage2:first-devops-assessment-latest

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"
          git add .
          git commit -m "updating newer image"
          git push --set-upstream origin main
