name: DevOps Assessments

on:
  push:
    branches:
      - main

jobs:
  devops-assessment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        # run: docker login --username hafizshaikh --password-stdin Wohlig@123
        run: echo "Wohlig@123" | docker login --username hafizshaikh  --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t hafizshaikh/newimage3:first-devops-assessment-latest .
          docker push hafizshaikh/newimage3:first-devops-assessment-latest
