on:
  push:
    branches:
      - main

jobs:
  devops-assessment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub and push Docker image
        run: |
          docker login --username hafizshaikh --password Wohlig@123 && \
          docker build -t hafizshaikh/newimage3:first-devops-assessment-latest . && \
          docker push hafizshaikh/newimage3:first-devops-assessment-latest
