name: Devops-Assessment

on:
  push:
    branches:
      - main

jobs:
  devops-assessment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t first-devops-docker/first-devops-assessment:latest .
          docker push first-devops-docker/first-devops-assessment:latest


          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@wohlig.com"

          git add .
          git commit -m "updating newer image"
          git push --set-upstream origin main
